version: '3'
services:
  eureka-service:
    image: lk.chethana/eureka:1.0.0
    ports:
      - 8761:8761
  book-service:
    image: lk.chethana/bookservice:1.0.0
    depends_on:
      - eureka-service
      - admin-server
      - zipkin-server
    network_mode: host
  lend-service:
    image: lk.chethana/lend-service:1.0.0
    depends_on:
      - eureka-service
      - admin-server
    network_mode: host
  customer-service:
    image: lk.chethana/customer-service:1.0.0
    depends_on:
      - eureka-service
      - admin-server
      - zipkin-server
    network_mode: host
  apigateway:
    image: lk.chethana/apigateway:1.0.0
    ports:
      - 8081:8081
    depends_on:
      - eureka-service
      - book-service
      - lend-service
      - customer-service
      - admin-server
      - zipkin-server
    network_mode: host
  admin-server:
    image: lk.chethana/admin-server:1.0.0
    ports:
      - 8088:8088
    depends_on:
      - eureka-service
    network_mode: host
  zipkin-server:
    image: lk.chethana/zipkin-server:1.0.0
    ports:
      - 9411:9411
    depends_on:
      - eureka-service
    network_mode: host
   library-ui:
     image: lk.chethana/library-ui:1.0.0
     ports:
       - 4200:4200
     depends_on:
       - eureka-service
       - book-service
       - lend-service
       - customer-service
       - apigateway
     network_mode: host


